<?php

namespace Payments;

class RequestTokenAuth extends RequestToken
{

    protected $_params = [
        "action"                             => [
            "type"   => "mandatory",
            "values" => [Payments::ACTION_AUTH, Payments::ACTION_PURCHASE],
        ],
        "merchantId"                         => ["type" => "mandatory"],
        "password"                           => ["type" => "mandatory"],
        "timestamp"                          => ["type" => "mandatory"],
        "allowOriginUrl"                     => ["type" => "mandatory"],
        "channel"                            => ["type" => "mandatory"],
        "amount"                             => ["type" => "mandatory"],
        "currency"                           => ["type" => "mandatory"],
        "country"                            => ["type" => "mandatory"],
        "paymentSolutionId"                  => ["type" => "mandatory"],
        "merchantNotificationUrl"            => ["type" => "mandatory"],
        "customerId"                         => [
            "type"      => "conditional",
            "mandatory" => ["paymentMethod" => "CreditCard"],
        ],
        "customerDocumentNumber"             => [
            "type"      => "conditional",
            "mandatory" => ["customerDocumentType" => "isset"],
        ],
        "payerDocumentNumber"                => [
            "type"      => "conditional",
            "mandatory" => ["payerDocumentType" => "isset"],
        ],
        "merchantTxId"                       => ["type" => "optional"],
        "brandId"                            => ["type" => "optional"],
        "userDevice"                         => ["type" => "optional"],
        "userAgent"                          => ["type" => "optional"],
        "taxAmount"                          => ["type" => "optional"],
        "shippingAmount"                     => ["type" => "optional"],
        "chargeAmount"                       => ["type" => "optional"],
        "discountAmount"                     => ["type" => "optional"],
        "language"                           => ["type" => "optional"],
        "s_text1"                            => ["type" => "optional"],
        "s_text2"                            => ["type" => "optional"],
        "s_text3"                            => ["type" => "optional"],
        "s_text4"                            => ["type" => "optional"],
        "s_text5"                            => ["type" => "optional"],
        "d_date1"                            => ["type" => "optional"],
        "d_date2"                            => ["type" => "optional"],
        "d_date3"                            => ["type" => "optional"],
        "d_date4"                            => ["type" => "optional"],
        "d_date5"                            => ["type" => "optional"],
        "b_bool1"                            => ["type" => "optional"],
        "b_bool2"                            => ["type" => "optional"],
        "b_bool3"                            => ["type" => "optional"],
        "b_bool4"                            => ["type" => "optional"],
        "b_bool5"                            => ["type" => "optional"],
        "n_num1"                             => ["type" => "optional"],
        "n_num2"                             => ["type" => "optional"],
        "n_num3"                             => ["type" => "optional"],
        "n_num4"                             => ["type" => "optional"],
        "n_num5"                             => ["type" => "optional"],
        "merchantLandingPageUrl"             => ["type" => "optional"],
        "firstTimeTransaction"               => ["type" => "optional"],
        "customerDocumentType"               => ["type" => "optional"],
        "customerFirstName"                  => ["type" => "optional"],
        "customerLastName"                   => ["type" => "optional"],
        "customerSex"                        => ["type" => "optional"],
        "customerDateOfBirth"                => ["type" => "optional"],
        "customerRegistrationDate"           => ["type" => "optional"],
        "customerEmail"                      => ["type" => "optional"],
        "customerPhone"                      => ["type" => "optional"],
        "customerIPAddress"                  => ["type" => "optional"],
        "customerCountry"                    => ["type" => "optional"],
        "customerAddressHouseName"           => ["type" => "optional"],
        "customerAddressHouseNumber"         => ["type" => "optional"],
        "customerAddressFlat"                => ["type" => "optional"],
        "customerAddressStreet"              => ["type" => "optional"],
        "customerAddressCity"                => ["type" => "optional"],
        "customerAddressDistrict"            => ["type" => "optional"],
        "customerAddressPostalCode"          => ["type" => "optional"],
        "customerAddressCountry"             => ["type" => "optional"],
        "customerAddressState"               => ["type" => "optional"],
        "customerAddressPhone"               => ["type" => "optional"],
        "customerShippingAddressHouseName"   => ["type" => "optional"],
        "customerShippingAddressHouseNumber" => ["type" => "optional"],
        "customerShippingAddressFlat"        => ["type" => "optional"],
        "customerShippingAddressStreet"      => ["type" => "optional"],
        "customerShippingAddressCity"        => ["type" => "optional"],
        "customerShippingAddressDistrict"    => ["type" => "optional"],
        "customerShippingAddressPostalCode"  => ["type" => "optional"],
        "customerShippingAddressCountry"     => ["type" => "optional"],
        "customerShippingAddressState"       => ["type" => "optional"],
        "customerShippingAddressPhone"       => ["type" => "optional"],
        "customerBillingAddressHouseName"    => ["type" => "optional"],
        "customerBillingAddressHouseNumber"  => ["type" => "optional"],
        "customerBillingAddressFlat"         => ["type" => "optional"],
        "customerBillingAddressStreet"       => ["type" => "optional"],
        "customerBillingAddressCity"         => ["type" => "optional"],
        "customerBillingAddressDistrict"     => ["type" => "optional"],
        "customerBillingAddressPostalCode"   => ["type" => "optional"],
        "customerBillingAddressCountry"      => ["type" => "optional"],
        "customerBillingAddressState"        => ["type" => "optional"],
        "customerBillingAddressPhone"        => ["type" => "optional"],
        "payerFirstName"                     => ["type" => "optional"],
        "payerLastName"                      => ["type" => "optional"],
        "payerEmail"                         => ["type" => "optional"],
        "payerDateOfBirth"                   => ["type" => "optional"],
        "payerPhone"                         => ["type" => "optional"],
        "payerDocumentType"                  => ["type" => "optional"],
        "payerCustomerId"                    => ["type" => "optional"],
        "forceSecurePayment"                 => ["type" => "optional"],
        "processUnknownSecurePayment"        => ["type" => "optional"],
        "specinCreditCardToken"              => ["type" => "optional"],
        "specinProcessWithoutCvv2"           => ["type" => "optional"],
        "bankMid"                            => ["type" => "optional"],
    ];

    public function __construct()
    {
        parent::__construct();
        $this->_data["action"] = Payments::ACTION_AUTH;
    }

}
